# configuration for https://rust-lang.github.io/rustfmt/
edition = "2024"
style_edition = "2024"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
wrap_comments = true
comment_width = 100
format_code_in_doc_comments = true
format_strings = true
max_width = 130
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true

