# Linting HTML and CSS for Web GUI

name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  html-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: HTML5_Validation
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: src/wgui/
          log_level: INFO
          config: html5validator_cfg.yaml


  css-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: stylelint
        uses: sww1235/stylelint_gh_action@master
        env:
          PATTERN: "src/wgui/styles/*.css"
      - uses: actions/upload-artifact@v4
        with:
          name: log
          path: log.log
